/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.DAO;
import br.com.senai.modelo.BebidaBean;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;

/**
 *
 * @author TI01N-2
 */
public class CadastroBebidaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroBebidaFrame
     */
    public CadastroBebidaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPanel = new JPanel();
        nomeLabel = new JLabel();
        nomeTextField = new JTextField();
        precoLabel = new JLabel();
        precoTextField = new JTextField();
        quantidadeLabel = new JLabel();
        quantidadeTextField = new JTextField();
        limparButton = new JButton();
        salvarButton = new JButton();
        tituloLabel = new JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Bebidas");
        setFrameIcon(new ImageIcon(getClass().getResource("/br/com/senai/view/images/addDrink.png"))); // NOI18N

        nomeLabel.setFont(new Font("sansserif", 0, 14)); // NOI18N
        nomeLabel.setText("Nome: ");

        precoLabel.setFont(new Font("sansserif", 0, 14)); // NOI18N
        precoLabel.setText("Preço: ");

        quantidadeLabel.setFont(new Font("sansserif", 0, 14)); // NOI18N
        quantidadeLabel.setText("Quantidade: ");

        limparButton.setFont(new Font("sansserif", 0, 14)); // NOI18N
        limparButton.setText("Limpar");
        limparButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        salvarButton.setFont(new Font("sansserif", 0, 14)); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        tituloLabel.setFont(new Font("sansserif", 1, 24)); // NOI18N
        tituloLabel.setHorizontalAlignment(SwingConstants.CENTER);
        tituloLabel.setText("Cadastro de Bebidas");

        GroupLayout fundoPanelLayout = new GroupLayout(fundoPanel);
        fundoPanel.setLayout(fundoPanelLayout);
        fundoPanelLayout.setHorizontalGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloLabel, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoPanelLayout.createSequentialGroup()
                        .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(precoLabel)
                            .addComponent(nomeLabel)
                            .addComponent(quantidadeLabel))
                        .addGap(31, 31, 31)
                        .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeTextField, GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(precoTextField)
                            .addComponent(quantidadeTextField)))
                    .addGroup(fundoPanelLayout.createSequentialGroup()
                        .addComponent(salvarButton, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(limparButton, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        fundoPanelLayout.setVerticalGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(28, 28, 28)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(precoLabel)
                    .addComponent(precoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeLabel)
                    .addComponent(quantidadeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(limparButton)
                    .addComponent(salvarButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(fundoPanel, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        BebidaBean bebida = new BebidaBean();
        DAO dao = new DAO();
        try {
            
            if (nomeTextField.getText().isEmpty() || precoTextField.getText().isEmpty() || quantidadeTextField.getText().isEmpty()){
                throw new NumberFormatException("Campos vazios");
            }
            
            if (Double.parseDouble(precoTextField.getText()) <= 0) {
                throw new NumberFormatException("Preço inválido");
            } else if (Integer.parseInt(quantidadeTextField.getText()) <= 0) {
                throw new NumberFormatException("Quantidade inválida");
            }
            
            bebida.setNome(nomeTextField.getText());
            bebida.setPreco(Double.parseDouble(precoTextField.getText()));
            bebida.setQuantidade(Integer.parseInt(quantidadeTextField.getText()));

            try {
                dao.cadastraBebida(bebida);
                JOptionPane.showMessageDialog(this, "Bebida salvo com sucesso.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Bebida " + nomeTextField.getText() + " já existe", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_salvarButtonActionPerformed

    private void limparButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        nomeTextField.setText("");
        precoTextField.setText("");
        quantidadeTextField.setText("");
    }//GEN-LAST:event_limparButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel fundoPanel;
    private JButton limparButton;
    private JLabel nomeLabel;
    private JTextField nomeTextField;
    private JLabel precoLabel;
    private JTextField precoTextField;
    private JLabel quantidadeLabel;
    private JTextField quantidadeTextField;
    private JButton salvarButton;
    private JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
