/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.DAO;
import br.com.senai.modelo.ClienteBean;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;

/**
 *
 * @author TI01N-2
 */
public class CadastroClienteFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroClienteFrame
     */
    public CadastroClienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPanel = new JPanel();
        nomeLabel = new JLabel();
        nomeTextField = new JTextField();
        idadeLabel = new JLabel();
        idadeTextField = new JTextField();
        cpfLabel = new JLabel();
        cpfTextField = new JTextField();
        limparButton = new JButton();
        salvarButton = new JButton();
        tituloLabel = new JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        setFrameIcon(new ImageIcon(getClass().getResource("/br/com/senai/view/images/addClient.png"))); // NOI18N

        nomeLabel.setFont(new Font("sansserif", 0, 14)); // NOI18N
        nomeLabel.setText("Nome: ");

        idadeLabel.setFont(new Font("sansserif", 0, 14)); // NOI18N
        idadeLabel.setText("Idade: ");

        cpfLabel.setFont(new Font("sansserif", 0, 14)); // NOI18N
        cpfLabel.setText("CPF: ");

        limparButton.setFont(new Font("sansserif", 0, 14)); // NOI18N
        limparButton.setText("Limpar");
        limparButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        salvarButton.setFont(new Font("sansserif", 0, 14)); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        tituloLabel.setFont(new Font("sansserif", 1, 24)); // NOI18N
        tituloLabel.setHorizontalAlignment(SwingConstants.CENTER);
        tituloLabel.setText("Cadastro de Clientes");

        GroupLayout fundoPanelLayout = new GroupLayout(fundoPanel);
        fundoPanel.setLayout(fundoPanelLayout);
        fundoPanelLayout.setHorizontalGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(fundoPanelLayout.createSequentialGroup()
                        .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(idadeLabel)
                            .addComponent(nomeLabel)
                            .addComponent(cpfLabel))
                        .addGap(34, 34, 34)
                        .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cpfTextField, GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(idadeTextField, GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTextField, GroupLayout.Alignment.LEADING)))
                    .addGroup(fundoPanelLayout.createSequentialGroup()
                        .addComponent(salvarButton, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(limparButton, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloLabel))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        fundoPanelLayout.setVerticalGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(33, 33, 33)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeLabel)
                    .addComponent(idadeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(fundoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(limparButton)
                    .addComponent(salvarButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(fundoPanel, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        ClienteBean cliente = new ClienteBean();
        DAO dao = new DAO();
        try {
            if (nomeTextField.getText().isEmpty() || idadeTextField.getText().isEmpty() || cpfTextField.getText().isEmpty()) {
                throw new NumberFormatException("Campos vazios");
            }

            if (Integer.parseInt(idadeTextField.getText()) <= 0) {
                throw new NumberFormatException("Idade inválida");
            } else if (Integer.parseInt(idadeTextField.getText()) <= 18) {
                throw new NumberFormatException("Cliente menor de 18 anos");
            }

            cliente.setNomeCliente(nomeTextField.getText());
            cliente.setIdadeCliente(Integer.parseInt(idadeTextField.getText()));
            cliente.setCpfCliente(cpfTextField.getText());

            try {
                dao.cadastraCliente(cliente);
                JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cliente " + nomeTextField.getText() + " já existe", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_salvarButtonActionPerformed

    private void limparButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        nomeTextField.setText("");
        cpfTextField.setText("");
        idadeTextField.setText("");
    }//GEN-LAST:event_limparButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel cpfLabel;
    private JTextField cpfTextField;
    private JPanel fundoPanel;
    private JLabel idadeLabel;
    private JTextField idadeTextField;
    private JButton limparButton;
    private JLabel nomeLabel;
    private JTextField nomeTextField;
    private JButton salvarButton;
    private JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
