/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.DAO;
import br.com.senai.modelo.ClienteBean;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.regex.PatternSyntaxException;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.RowFilter;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TI01N-2
 */
public class ConsultaClienteFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaClienteFrame
     */
    private DefaultTableModel tabela;
    private TableRowSorter<TableModel> sorter;

    public ConsultaClienteFrame() {
        initComponents();
        tabela = (DefaultTableModel) jTableConsultaCliente.getModel();
        sorter = new TableRowSorter<TableModel>(tabela);
        jTableConsultaCliente.setRowSorter(sorter);

        jComboBoxCampo.addItem("Todos");
        for (int x = 0; x < jTableConsultaCliente.getColumnCount(); x++) {
            jComboBoxCampo.addItem(jTableConsultaCliente.getColumnName(x));
        }
        atualizaComboBox();

        jButtonConsultaClienteActionPerformed(null);

    }

    public void atualizaComboBox() {
        DAO dao = new DAO();

        jComboBoxCampoAtualiza.removeAllItems();

        ArrayList<ClienteBean> listaCliente = dao.getListaCliente();

        for (ClienteBean cliente : listaCliente) {
            jComboBoxCampoAtualiza.addItem(cliente.getNomeCliente());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new JPanel();
        jLabelTitulo = new JLabel();
        jLabelFiltro = new JLabel();
        jTextFieldFiltro = new JTextField();
        jButtonConsultaCliente = new JButton();
        jScrollPane1 = new JScrollPane();
        jTableConsultaCliente = new JTable();
        jComboBoxCampo = new JComboBox();
        jPanelAtualiza = new JPanel();
        jButtonAtualiza = new JButton();
        jCheckBoxNome = new JCheckBox();
        jComboBoxCampoAtualiza = new JComboBox();
        jCheckBoxIdade = new JCheckBox();
        jCheckBoxCpf = new JCheckBox();
        jButtonDeleta = new JButton();
        jTextFieldCpf = new JTextField();
        jTextFieldIdade = new JTextField();
        jTextFieldNome = new JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Dados do Cliente");
        setFrameIcon(new ImageIcon(getClass().getResource("/br/com/senai/view/images/client.png"))); // NOI18N

        jLabelTitulo.setFont(new Font("sansserif", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelTitulo.setText("Dados do Cliente");

        jLabelFiltro.setText("Filtro:");

        jButtonConsultaCliente.setText("Consultar");
        jButtonConsultaCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonConsultaClienteActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableConsultaCliente.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Idade", "CPF", "Valor Gasto"
            }
        ));
        jScrollPane1.setViewportView(jTableConsultaCliente);

        jComboBoxCampo.setLightWeightPopupEnabled(false);
        jComboBoxCampo.setMaximumSize(new Dimension(120, 26));
        jComboBoxCampo.setPreferredSize(new Dimension(120, 26));

        jPanelAtualiza.setBorder(BorderFactory.createTitledBorder(null, "Atualizar:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("sansserif", 1, 14))); // NOI18N
        jPanelAtualiza.setOpaque(false);

        jButtonAtualiza.setText("Atualizar");
        jButtonAtualiza.setEnabled(false);
        jButtonAtualiza.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonAtualizaActionPerformed(evt);
            }
        });

        jCheckBoxNome.setText("Alterar Nome:");
        jCheckBoxNome.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                jCheckBoxNomeItemStateChanged(evt);
            }
        });

        jCheckBoxIdade.setText("Alterar Idade:");
        jCheckBoxIdade.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                jCheckBoxIdadeItemStateChanged(evt);
            }
        });

        jCheckBoxCpf.setText("Alterar CPF:");
        jCheckBoxCpf.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                jCheckBoxCpfItemStateChanged(evt);
            }
        });

        jButtonDeleta.setText("Deletar");
        jButtonDeleta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonDeletaActionPerformed(evt);
            }
        });

        jTextFieldCpf.setEnabled(false);

        jTextFieldIdade.setEnabled(false);

        jTextFieldNome.setEnabled(false);

        GroupLayout jPanelAtualizaLayout = new GroupLayout(jPanelAtualiza);
        jPanelAtualiza.setLayout(jPanelAtualizaLayout);
        jPanelAtualizaLayout.setHorizontalGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtualizaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtualizaLayout.createSequentialGroup()
                        .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCpf)
                            .addComponent(jCheckBoxIdade)
                            .addComponent(jCheckBoxNome))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCpf, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdade, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxCampoAtualiza, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtualiza, GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDeleta, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)))
        );
        jPanelAtualizaLayout.setVerticalGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtualizaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCampoAtualiza, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNome)
                    .addComponent(jTextFieldNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxIdade)
                    .addComponent(jTextFieldIdade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleta))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAtualizaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCpf)
                    .addComponent(jTextFieldCpf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualiza))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        GroupLayout jPanelFundoLayout = new GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(jPanelFundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanelFundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(jLabelFiltro)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFiltro, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCampo, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultaCliente))
                    .addComponent(jPanelAtualiza, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelFundoLayout.setVerticalGroup(jPanelFundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFundoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultaCliente)
                    .addComponent(jLabelFiltro)
                    .addComponent(jTextFieldFiltro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCampo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAtualiza, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFundo, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultaClienteActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaClienteActionPerformed
        DAO dao = new DAO();
        //Cliente cliente = new ClienteBean();

        ArrayList<ClienteBean> listaCliente = dao.getListaCliente();

        tabela.setRowCount(0);

        for (ClienteBean cliente : listaCliente) {
            tabela.addRow(new Object[]{
                cliente.getIdCliente(),
                cliente.getNomeCliente(),
                cliente.getIdadeCliente(),
                cliente.getCpfCliente(),
                String.format("R$ %.2f", dao.getTotalGasto(cliente))
            });
        }

        String text = jTextFieldFiltro.getText();

        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                if (jComboBoxCampo.getSelectedIndex() == 0) {
                    sorter.setRowFilter(
                            RowFilter.regexFilter(text));
                } else {
                    sorter.setRowFilter(
                            RowFilter.regexFilter(text, jComboBoxCampo.getSelectedIndex() - 1));
                }
            } // end try
            catch (PatternSyntaxException pse) {
                JOptionPane.showMessageDialog(null,
                        "Bad regex pattern", "Bad regex pattern",
                        JOptionPane.ERROR_MESSAGE);
            } // end catch
        } // end else


    }//GEN-LAST:event_jButtonConsultaClienteActionPerformed

    private void atualizarTabela(){
        System.out.println(String.valueOf(jTableConsultaCliente.getValueAt(0, 2)));
    }
    
    private void jButtonAtualizaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizaActionPerformed
        this.atualizarTabela();
        boolean nome = jCheckBoxNome.isSelected();
        boolean cpf = jCheckBoxCpf.isSelected();
        boolean idade = jCheckBoxIdade.isSelected();
        DAO dao = new DAO();

        try {

            if (nome && !jTextFieldNome.getText().isEmpty()) {
                dao.atualizaNomeCliente((String) jComboBoxCampoAtualiza.getSelectedItem(), jTextFieldNome.getText());
            }

            if (idade && !jTextFieldIdade.getText().isEmpty()) {
                if (Integer.parseInt(jTextFieldIdade.getText()) <= 0) {
                    throw new NumberFormatException("Idade inválida");
                } else if (Integer.parseInt(jTextFieldIdade.getText()) <= 18) {
                    throw new NumberFormatException("Cliente menor de 18 anos");
                }
                dao.atualizaIdadeCliente((String) jComboBoxCampoAtualiza.getSelectedItem(), Integer.parseInt(jTextFieldIdade.getText()));
            }

            if (cpf && !jTextFieldCpf.getText().isEmpty()) {
                dao.atualizaCpfCliente((String) jComboBoxCampoAtualiza.getSelectedItem(), jTextFieldCpf.getText());

            }
            atualizaComboBox();
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso", "Atualizar", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        jButtonConsultaClienteActionPerformed(evt);
        jTextFieldNome.setText("");
        jTextFieldIdade.setText("");
        jTextFieldCpf.setText("");
        jCheckBoxNome.setSelected(false);
        jCheckBoxCpf.setSelected(false);
        jCheckBoxIdade.setSelected(false);
    }//GEN-LAST:event_jButtonAtualizaActionPerformed

    private void jCheckBoxNomeItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_jCheckBoxNomeItemStateChanged
        this.changeButtonAtualiza();

        if (jCheckBoxNome.isSelected()) {
            jTextFieldNome.setEnabled(true);
        } else {
            jTextFieldNome.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxNomeItemStateChanged

    private void jCheckBoxIdadeItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_jCheckBoxIdadeItemStateChanged
        this.changeButtonAtualiza();

        if (jCheckBoxIdade.isSelected()) {
            jTextFieldIdade.setEnabled(true);
        } else {
            jTextFieldIdade.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxIdadeItemStateChanged

    private void jCheckBoxCpfItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_jCheckBoxCpfItemStateChanged
        this.changeButtonAtualiza();

        if (jCheckBoxCpf.isSelected()) {
            jTextFieldCpf.setEnabled(true);
        } else {
            jTextFieldCpf.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxCpfItemStateChanged

    private void jButtonDeletaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonDeletaActionPerformed
        String nomeCliente = (String) jComboBoxCampoAtualiza.getSelectedItem();
        DAO dao = new DAO();
        dao.deletaCliente(this, nomeCliente);
        jComboBoxCampoAtualiza.removeItem(nomeCliente);
        jButtonConsultaClienteActionPerformed(evt);
    }//GEN-LAST:event_jButtonDeletaActionPerformed

    public void changeButtonAtualiza() {
        if (jCheckBoxNome.isSelected() || jCheckBoxIdade.isSelected() || jCheckBoxCpf.isSelected()) {
            jButtonAtualiza.setEnabled(true);
        } else {
            jButtonAtualiza.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonAtualiza;
    private JButton jButtonConsultaCliente;
    private JButton jButtonDeleta;
    private JCheckBox jCheckBoxCpf;
    private JCheckBox jCheckBoxIdade;
    private JCheckBox jCheckBoxNome;
    private JComboBox jComboBoxCampo;
    private JComboBox jComboBoxCampoAtualiza;
    private JLabel jLabelFiltro;
    private JLabel jLabelTitulo;
    private JPanel jPanelAtualiza;
    private JPanel jPanelFundo;
    private JScrollPane jScrollPane1;
    private JTable jTableConsultaCliente;
    private JTextField jTextFieldCpf;
    private JTextField jTextFieldFiltro;
    private JTextField jTextFieldIdade;
    private JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
