/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.dao.DAO;
import br.com.senai.modelo.BebidaBean;
import br.com.senai.modelo.ClienteBean;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author TI01N-2
 */
public class VendaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form VendaFrame
     */
    public VendaFrame() {
        initComponents();

        DAO dao = new DAO();

        ArrayList<ClienteBean> listaCliente = dao.getListaCliente();
        ArrayList<BebidaBean> listaBebida = dao.getListaBebida();

        for (ClienteBean cliente : listaCliente) {
            jComboBoxCliente.addItem(cliente.getNomeCliente());
        }
        for (BebidaBean bebida : listaBebida) {
            jComboBoxBebida.addItem(bebida.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFund = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jComboBoxCliente = new JComboBox();
        jComboBoxBebida = new JComboBox();
        jTextFieldQuantidade = new JTextField();
        jButtonFinalizar = new JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Venda");
        setFrameIcon(new ImageIcon(getClass().getResource("/br/com/senai/view/images/sale.png"))); // NOI18N

        jLabel1.setFont(new Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Venda de Bebidas");

        jLabel2.setFont(new Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Cliente: ");

        jLabel3.setFont(new Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Bebida:");

        jLabel4.setFont(new Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade");

        jButtonFinalizar.setFont(new Font("sansserif", 0, 14)); // NOI18N
        jButtonFinalizar.setText("Finalizar Venda");
        jButtonFinalizar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        GroupLayout jPanelFundLayout = new GroupLayout(jPanelFund);
        jPanelFund.setLayout(jPanelFundLayout);
        jPanelFundLayout.setHorizontalGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFinalizar)
                    .addComponent(jTextFieldQuantidade, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBebida, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCliente, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanelFundLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanelFundLayout.setVerticalGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxBebida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelFundLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldQuantidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonFinalizar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFund, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        DAO dao = new DAO();
        try {
            if(Double.parseDouble(jTextFieldQuantidade.getText()) <=0){
                throw new NumberFormatException();
            }
            if (!jTextFieldQuantidade.getText().isEmpty()) {
                dao.realizaVenda(this, (String) jComboBoxCliente.getSelectedItem(), (String) jComboBoxBebida.getSelectedItem(), Integer.parseInt(jTextFieldQuantidade.getText()));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Quantidade inválida", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonFinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonFinalizar;
    private JComboBox jComboBoxBebida;
    private JComboBox jComboBoxCliente;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanelFund;
    private JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
